### PR TITLE
fix: fixes issue #1200

### LINKED ISSUE #1200: Copied old session submission from monthly that.us doesn't convert properly to AT THAT submission
**Describe the bug**

When copying an accepted monthly That.us topic for That Conference Wisconsin in July, the session is automatically accepted and has a "Schedule the Time" section which needs to be filled out to submit the session. Looking at "My submissions", the submission shows itself as Accepted and shows the scheduled time that you entered.

**To Reproduce**

https://that.us/activities/edit/b6fuDVi75eny1lAMR6B2/

1. Start with a session that was accepted as a part of a monthly that.us event
2. Copy that submission into a new suibmission.
3. Change the scheduled location/event to That Conference Wisconsin
4. Scroll to the bottom of the page.
5. You should see a "Schedule the Time" section, which should not be on a normal "call for presenters" submission for That Conference Wisconsin
6. image
7. Fill out the submission information submit the session.
8. Go to your "My Submissions" page.
9. Your submitted section will show up as "Accepted" and lists the time that you chose.
image
 

**Expected behavior**
I expected the session submission to not include the "schedule the time" section, and the completed submission be listed as "submitted" at this point, not accepted.

**Screenshots**
See above.

**Desktop (please complete the following information):**

- OS: Win 10
- Browser Firefox Developer Edition
- Version 98.0b5

**Additional context**
Thanks for the help!

### PR DESCRIPTION
**Pull request by csell5**
activity type wasn't getting cleared in all cases.

fixes #1200

### CODE REVIEW

File: src/routes/activities/clone/index.svelte [hunk 1]
```diff
@@ -40,6 +40,7 @@
 	delete activity.id;
 	delete activity.eventId;
 	delete activity.event;
+	delete activity.type;
```
Comment (brettski) [inline src/routes/activities/clone/index.svelte:44]: Does the activity.startTime get carried over in a clone?

**Review by brettski — CHANGES_REQUESTED** [review]
One question

**Review by brettski — APPROVED** [review]
