### PR TITLE
Ticket and Membership Checks

### LINKED ISSUE #618: Member without event access creating session causes crash
**Describe the bug**
A member who doesn't have access to an event is still allowed to create that event. When they go to save it it causes a crash.

**To Reproduce**
1. Ensure you are logged in with a users who doesn't have access to and event (no membership and no ticket for event)
1. Go to add session: https://feature.that.us/activities/create/YWavA70szR8rxSwrLJaL
2. Click on **THAT Online - April** under the "UPCOMING ONLINE EVENTS"
3. Fill in the form to create a new session
4. click, **Submit Activity**
4. See error, crash report shows

**Expected behavior**
A user who doesn't have access to an event should not be able to select the event to submit a session for it.

**Screenshots**

**Desktop (please complete the following information):**
ant

**Smartphone (please complete the following information):**
any

**Additional context**

### LINKED ISSUE #636: Restrict join to members and ticket holders

### LINKED ISSUE #655: Your Settings->Merit Badges : Pressing "Reset" Causes Crash
**Describe the bug**
When the "Reset" button is pressed (whether or not there is data in the "Ticket Reference Number" field), the crash-box appears

**To Reproduce**
1. Go to Your Settings->Merit Badges
2. Click on '"Reset" button
3. Boom

**Expected behavior**
The "Reset" button should... ?   Um... what does the "Reset" button do?

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Safari

### PR DESCRIPTION
**Pull request by csell5**
Closes #618 
Closes #655 
Closes #636 

Fixes date format grammar.
Also handles end call-end redirects to /activities.

### CODE REVIEW

File: src/routes/activities/components/form/_Event.svelte [hunk 1]
```diff
@@ -166,52 +174,57 @@
...
+                {:else}
+                  <div
+                    class="flex-1 flex items-center justify-between border border-green-500 bg-green-100 rounded-md truncate">
+                    <div class="flex-1 px-4 py-2 text-sm truncate">
+                      <p class="text-gray-900 font-bold">
+                        {event.name}
+                      </p>
+
+                      <p class="text-gray-500">
+                        {dayjs(event.startDate).format('dddd MMMM D, YYYY')}
```
Comment (brettski) [inline src/routes/activities/components/form/_Event.svelte:211]: There should be a comma after the day so i.e. Monday, January 21, 2021

`'dddd, MMMM D, YYYY'`
https://www.grammarly.com/blog/how-to-write-dates/

**Review by brettski — CHANGES_REQUESTED** [review]

File: src/routes/activities/components/form/_Event.svelte (hunk 1 above)
Comment (csell5) [reply src/routes/activities/components/form/_Event.svelte]: ok, fixed it across the entire site.

**Review by brettski — APPROVED** [review]
